
### Configurations  ###

## General ##
server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
    gateway:
      routes:
      - id: user_route
        uri: lb://user-service
        predicates:
        - Path=/users/**
        filters:
            - RewritePath=/users/?(?<segment>.*), /$\{segment}
      - id: auth_route
        uri: lb://auth-service
        predicates:
        - Path=/auth/**
        filters:
            - RewritePath=/auth/?(?<segment>.*), /$\{segment}
      discovery:
        locator:
          enabled: true
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379